[project]
name = "workshop-python-aula18"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.10.4",
    "requests>=2.32.3",
    "sqlalchemy>=2.0.36",
]
